# LOAD PACKAGES!

In [1]:
import numpy as np
print ("Loading package(s)")

Loading package(s)


# PRINT function suages

In [2]:
print("Hello, world!")

# 1. STRING
x = "Hello, world"
print ("String: [%s], [%3s], [%20s]" % (x, x, x))

# 2. INTEGER
x = 3;
print ("Integer: %01d, %02d, %03d, %04d, %05d" % (x, x, x, x, x))

# 3. FLOAT
x = 123.456;
print ("Float: %.0f, %.1f, %.2f, %1.2f, %2.2f" % (x, x, x, x, x))

# 4. {}
a = "Today"
b = "is"
y = 2018
m = 4
d = 20
print("{} {} {}.{:02}.{}".format(a,b,y,m,d))

Hello, world!
String: [Hello, world], [Hello, world], [        Hello, world]
Integer: 3, 03, 003, 0003, 00003
Float: 123, 123.5, 123.46, 123.46, 123.46
Today is 2018.04.20


# FOR + IF/ELSE

In [3]:
rlmethods = ["BELLMAN EQUATION", "BELLMAN OPTIMALITY", "VALUE ITERATION", "POLICY ITERATION", "ACTOR CRITIC METHODS", "POLICY GRADIENT"]

for alg in rlmethods:
    if alg=="BELLMAN EQUATION":
        print ("We have seen %s" % (alg))

for alg in rlmethods:
    if alg in [ "BELLMAN OPTIMALITY", "VALUE ITERATION", "POLICY ITERATION"]:
        print ("We will see %s" % (alg))

We have seen BELLMAN EQUATION
We will see BELLMAN OPTIMALITY
We will see VALUE ITERATION
We will see POLICY ITERATION


# FOR LOOP WITH INDEX

In [4]:
# Little more advanced?
print("\nFOR loop with index.")
for alg, i in zip(rlmethods, range(len(rlmethods))):
    if alg in ["VALUE ITERATION"]:
        print ("[%d/%d] %s is a value-based method." 
               % (i, len(rlmethods), alg))
    elif alg in ["POLICY ITERATION", "ACTOR CRITIC METHODS"]:
        print ("[%d/%d] %s is a policy and value based method." 
               % (i, len(rlmethods), alg))
    elif alg in ["POLICY GRADIENT"]:
        print ("[%d/%d] %s is a policy-based method." 
               % (i, len(rlmethods), alg))
    else:
        print("[%d/%d] %s is a core equation." 
               % (i, len(rlmethods), alg))


FOR loop with index.
[0/6] BELLMAN EQUATION is a core equation.
[1/6] BELLMAN OPTIMALITY is a core equation.
[2/6] VALUE ITERATION is a value-based method.
[3/6] POLICY ITERATION is a policy and value based method.
[4/6] ACTOR CRITIC METHODS is a policy and value based method.
[5/6] POLICY GRADIENT is a policy-based method.


## Note that, index starts with 0!

# FUNCTIONS

In [5]:
# Function definition looks like this
def sum(a, b):
    return a+b
X = 10.
Y = 20.
# Usage 
print ("%.1f + %.1f = %.1f" % (X, Y, sum(X, Y)))

10.0 + 20.0 = 30.0


# STRING

In [7]:
head = "Reinforcement learning" 
body = "very "
tail = "HARD."
print (head + " is " + body + tail)

# Repeat words
print (head + " is " + body*3 + tail)
print (head + " is " + body*10 + tail)

# It is used in this way
print ("\n" + "="*50)
print (" "*15 + "It is used in this way")
print ("="*50 + "\n")

# Indexing characters in the string
x = "Hello, world" 
for i in range(len(x)):
    print ("Index: [%02d/%02d] Char: %s" 
           % (i, len(x), x[i]))

Reinforcement learning is very HARD.
Reinforcement learning is very very very HARD.
Reinforcement learning is very very very very very very very very very very HARD.

               It is used in this way

Index: [00/12] Char: H
Index: [01/12] Char: e
Index: [02/12] Char: l
Index: [03/12] Char: l
Index: [04/12] Char: o
Index: [05/12] Char: ,
Index: [06/12] Char:  
Index: [07/12] Char: w
Index: [08/12] Char: o
Index: [09/12] Char: r
Index: [10/12] Char: l
Index: [11/12] Char: d


In [8]:
# More indexing 
print("")
idx = -2
print("(%d)th char is %s" % (idx, x[idx]))
idxfr = 0
idxto = 8
print("String from %d to %d is [%s]" 
       % (idxfr, idxto, x[idxfr:idxto]))
idxfr = 4
print("String from %d to END is [%s]" 
       % (idxfr, x[idxfr:]))
x = "20160607Cloudy"
year = x[:4]
day = x[4:8]
weather = x[8:]
print("[%s] -> [%s] + [%s] + [%s] " 
       % (x, year, day, weather))


(-2)th char is l
String from 0 to 8 is [Hello, w]
String from 4 to END is [o, world]
[20160607Cloudy] -> [2016] + [0607] + [Cloudy] 


# LIST

In [ ]:
a = []
b = [1, 2, 3]
c = ["Hello", ",", "world"]
d = [1, 2, 3, "x", "y", "z"]
x = []
print(x)
x.append('a')
print(x)
x.append(123)
print(x)
x.append(["a", "b"])
print(x)
print("Length of x is %d " 
      % (len(x)))
for i in range(len(x)):
    print("[%02d/%02d] %s" 
           % (i, len(x), x[i]))

[]
['a']
['a', 123]
['a', 123, ['a', 'b']]
Length of x is 3 
[00/03] a
[01/03] 123
[02/03] ['a', 'b']


In [ ]:
z = []
z.append(1)
z.append(2)
z.append(3)
z.append('Hello')
for i in range(len(z)):
    print (z[i])

# DICTIONARY

In [ ]:
dic = dict()
dic["name"] = "Kyungjae"
dic["age"] = 27
dic["job"] = "Ph.D. Candidate"

print(dic.keys())
print(dic)

In [ ]:
dic = {"name":"Kyungjae","age":27,"job":"Ph.D. Candidate"}

print(dic.keys())
print(dic)

# Class

In [ ]:
class Greeter:

    # Constructor
    def __init__(self, name):
        self.name = name  # Create an instance variable

    # Instance method
    def greet(self, loud=False):
        if loud:
            print ('HELLO, %s!' 
                   % self.name.upper())
        else:
            print ('Hello, %s' 
                   % self.name)

g = Greeter('Fred')  # Construct an instance of the Greeter class
g.greet()            # Call an instance method; prints "Hello, Fred"
g.greet(loud=True)   # Call an instance method; prints "HELLO, FRED!"

# NUMPY

In [ ]:
def print_np(x):
    print ("Type is %s" % (type(x)))
    print ("Shape is %s" % (x.shape,))
    print ("Values are: \n%s" % (x))
    print

# RANK 1 ARRAY

In [ ]:
x = np.array([1, 2, 3]) # rank 1 array
print_np(x)

x[0] = 5
print_np(x)

# RANK 2 ARRAY

In [ ]:
y = np.array([[1,2,3], [4,5,6]]) 
print_np(y)

# RANK 2 ZEROS

In [ ]:
a = np.zeros((3, 2))  
print_np(a)

# RANK 2 ONES

In [ ]:
b = np.ones((1, 2))   
print_np(b)

# RANK 2 IDENTITY 

In [ ]:
c = np.eye(2, 2)   
print_np(c)

# RANDOM MATRIX (UNIFORM)

In [ ]:
d = np.random.random((2, 2))    
print_np(d)

# RANDOM MATRIX (GAUSSIAN)


In [ ]:
e = np.random.randn(1, 10)    
print_np(e)

# ARRAY INDEXING

In [ ]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print_np(a)

print
# Use slicing to pull out the subarray consisting 
# of the first 2 rows
# and columns 1 and 2; b is the following array 
# of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print_np(b)

# GET ROW

In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print_np(a)

row_r1 = a[1, :]    # Rank 1 view of the second row of a  
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
row_r3 = a[[1], :]  # Rank 2 view of the second row of a

print_np(row_r1)
print_np(row_r2)
print_np(row_r3)

# DATATYPES

In [ ]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # particular datatype

print_np(x)
print_np(y)
print_np(z)

# Array math

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))

In [ ]:
#  Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

In [ ]:
# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))

In [ ]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

In [ ]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print (np.sqrt(x))

# MATRIX OPERATION

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11, 12])

print_np(x)
print_np(y)
print_np(v)
print_np(w)

# VECTORS-VECTORS OPERATION

In [ ]:
# Inner product of vectors; both produce 219
print_np(v.dot(w))
print_np(np.dot(v, w)) # <= v * w

# MATRIX-VECTOR OPERATION

In [ ]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print_npprint_np(x.dot(v))
print_np(np.dot(x, v)) # <= x * v'

# MATRIX-MATRIX OPERATION

In [ ]:
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print_np(x.dot(y))
print_np(np.dot(x, y))

# TRANSPOSE

In [ ]:
x = np.array([[1,2],[3,4]])
print_np(x)
print_np(x.T)

In [ ]:
v = np.array([1,2,3])
print_np(v) 
print_np(v.T)

In [ ]:
v = np.array([[1,2,3]])
print_np(v) 
print_np(v.T)

# Other useful operations


In [ ]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)    # Create an empty matrix 
                        # with the same shape as x

print_np(x)
print_np(v)
print_np(y)

In [ ]:
# Add the vector v to each row of the matrix x 
# with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v
print_np(y)

In [ ]:
vv = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other
print_np(vv)             # Prints "[[1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]]"

In [ ]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using BROADCASTING
print_np(x)
print_np(v)
print_np(y)

In [ ]:
# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])

print_np(x)
print_np(v)
print(x + v)

In [ ]:
# Add a vector to each column of a matrix
print_np(x)
print_np(w)
print((x.T + w).T)

# Another solution is to reshape w 
# to be a row vector of shape (2, 1);
print
print(x + np.reshape(w, (2, 1)))

# Matplotlib

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
# Compute the x and y coordinates for points on a sine curve
x = np.arange(0, 3 * np.pi, 0.1)
y = np.sin(x)

# Plot the points using matplotlib
plt.plot(x, y)

In [ ]:
y_sin = np.sin(x)
y_cos = np.cos(x)
# Plot the points using matplotlib
plt.plot(x, y_sin)
plt.plot(x, y_cos)
plt.xlabel('x axis label')
plt.ylabel('y axis label')
plt.title('Sine and Cosine')
plt.legend(['Sine', 'Cosine'])

# Show the figure.
plt.show()

In [ ]:
# Compute the x and y coordinates for points 
# on sine and cosine curves
x = np.arange(0, 3 * np.pi, 0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)

# Set up a subplot grid that has height 2 and width 1,
# and set the first such subplot as active.
plt.subplot(2, 1, 1)

# Make the first plot
plt.plot(x, y_sin)
plt.title('Sine')

# Set the second subplot as active, and make the second plot.
plt.subplot(2, 1, 2)
plt.plot(x, y_cos)
plt.title('Cosine')

# Show the figure.
plt.show()